id: c0cc25c3-c0b2-4fb6-bd46-1168bf4b52b8
metadata:
  name: 'Session configuration: Cookies: Set Secure flag to true '
  shortDescription: Prevent a cookie being sent over unencrypted HTTP by setting the
    Secure flag to true
  level: error
  scwCategory: improper_session_handling
  enabled: true
  descriptionFile: SessionconfigurationCookiesSetSecureflagtotrue.html
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "false"
    name:
      matches: setUseSecureCookie
    type: org.springframework.session.web.http.DefaultCookieSerializer
availableFixes:
- name: Set Secure to true
  actions:
  - modifyArguments:
      rewrite:
        1: "true"
