id: 669692d8-e798-4df2-91b0-3463c947f83e
version: 8
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Avoid DefaultHttpFirewall
    (instance creation)'
  shortDescription: Using DefaultHttpFirewall may lead to security flaws
  level: warning
  scwCategory: ""
  enabled: true
  descriptionFile: SecurityMisconfigurationAvoidDefaultHttpFirewallInstanceCreation.html
search:
  instanceCreation:
    type: org.springframework.security.web.firewall.DefaultHttpFirewall
availableFixes:
- name: Use StrictHttpFirewall
  actions:
  - rewrite:
      to: new org.springframework.security.web.firewall.StrictHttpFirewall()
  - modifyAssignedVariable:
      type: org.springframework.security.web.firewall.StrictHttpFirewall
