id: ef1d439a-75e5-42a0-990d-28ed51d24850
version: 8
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Rule configuration: Reject
    (URL encoded) backslash'
  shortDescription: Rejecting the use of a (URL encoded) backslash is more secure
  level: warning
  scwCategory: ""
  enabled: true
  descriptionFile: SecurityMisconfigurationStrictHttpFirewallRuleconfigurationrejectbackslash.html
search:
  methodcall:
    args:
      1:
        type: boolean
    name: setAllowBackSlash
    type: org.springframework.security.web.firewall.StrictHttpFirewall
availableFixes:
- name: Set .setAllowBackSlash() to false
  actions:
  - modifyArguments:
      rewrite:
        1: "false"
