id: 00dc48c2-9709-4ad6-b50d-7e38b628c0f5
metadata:
  name: 'Security Misconfiguration: Content sniffing protection'
  shortDescription: Prevent MIME sniffing by disabling contentTypeOptions
  level: error
  scwCategory: misconfig
  enabled: true
  descriptionFile: SecurityMisconfigurationContentsniffingprotection.html
search:
  methodcall:
    not:
      followedBy:
        methodcall:
          name: disable
    name: contentTypeOptions
    declaration:
      type: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer
    "on":
      methodcall:
        name: headers
availableFixes:
- name: Disable contentTypeOptions
  actions:
  - rewrite:
      to: '{{{ . }}}.disable()'
