id: 8dcc914f-bf2c-4d50-a9fd-3e7e117c5339
metadata:
  name: 'Security Misconfiguration: Disabled Headers'
  shortDescription: Disabling Spring Security's default headers makes the application
    vulnerable
  level: warning
  scwCategory: misconfig
  enabled: true
  descriptionFile: SecurityMisconfigurationDisabledHeaders.html
search:
  methodcall:
    in:
      typeDeclaration:
        super:
          name: org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter
    name:
      matches: defaultsDisabled|disable
    declaration:
      type:
        reference:
          matches: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer|AbstractHttpConfigurer
        checkInheritance: true
availableFixes:
- name: Enable default headers
  actions:
  - rewrite:
      to: '{{{ qualifier }}}'
