id: eef53ef1-5079-4c5b-bf75-00be333f8032
metadata:
  name: 'Security Misconfiguration: HSTS - includeSubDomains'
  shortDescription: Include subdomains in the HSTS domain
  level: error
  scwCategory: misconfig
  enabled: true
  descriptionFile: SecurityMisconfigurationHSTS-includeSubDomains.html
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "false"
    name: includeSubDomains
    declaration:
      type: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer.HstsConfig
availableFixes:
- name: Set includeSubDomains to true
  actions:
  - modifyArguments:
      rewrite:
        1: "true"
