id: acf679f4-8499-4984-b2b3-e590e689ab92
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Rule configuration: Reject
    URL encoded double slash'
  shortDescription: Rejecting the use of a URL encoded double slash in the URL is
    more secure
  level: warning
  scwCategory: ""
  enabled: true
  descriptionFile: SecurityMisconfigurationStrictHttpFirewallRuleconfigurationRejectURLencodeddoubleslash.html
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "true"
    name: setAllowUrlEncodedDoubleSlash
    type: org.springframework.security.web.firewall.StrictHttpFirewall
availableFixes:
- name: Set .setAllowUrlEncodedDoubleSlash() to false
  actions:
  - modifyArguments:
      rewrite:
        1: "false"
