id: 9cadcb2c-8338-4606-8329-a48e70113d43
metadata:
  name: 'Security Misconfiguration: Disable Security Features - HSTS'
  shortDescription: Enforce HSTS protection against vulnerabilities over HTTP
  level: error
  scwCategory: misconfig
  enabled: true
  descriptionFile: SecurityMisconfigurationDisableSecurityFeatures-HSTS.html
search:
  methodcall:
    name: disable
    declaration:
      type: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer.HstsConfig
    "on":
      methodcall:
        name: httpStrictTransportSecurity
        declaration:
          type: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer
availableFixes:
- name: Enable HSTS
  actions:
  - rewrite:
      to: '{{{ qualifier }}}'
