id: a9865f59-0025-46f3-bbe2-111ec56636dd
metadata:
  name: 'Security Misconfiguration: XSS protection: Disabled Header - xssProtectionEnabled()'
  shortDescription: Do not disable Spring Security's built-in XSS protection
  level: warning
  scwCategory: xss
  enabled: true
  descriptionFile: SecurityMisconfigurationDisabledXSSprotectioninSpringSecurity-xssProtectionEnabled.html
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "false"
    in:
      typeDeclaration:
        super:
          name: org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter
    name: xssProtectionEnabled
    declaration:
      type: org.springframework.security.config.annotation.web.configurers.HeadersConfigurer.XXssConfig
availableFixes:
- name: Enable XssProtection
  actions:
  - modifyArguments:
      rewrite:
        1: "true"
