id: 3162ab4b-639d-4b61-9a11-bdc7af383a89
version: 8
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Rule configuration: Reject
    semicolon'
  shortDescription: Rejecting semicolons is more secure
  level: warning
  scwCategory: ""
  enabled: true
  descriptionFile: StrictHttpFirewallRuleconfigurationrejectsemicolons.html
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "true"
    name: setAllowSemicolon
    type: org.springframework.security.web.firewall.StrictHttpFirewall
availableFixes:
- name: Set .setAllowSemicolon() to false
  actions:
  - modifyArguments:
      rewrite:
        1: "false"
