id: 675917a7-7dcb-40db-9a25-f3a2167a0457
version: 8
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Avoid DefaultHttpFirewall
    (method return type)'
  shortDescription: Using DefaultHttpFirewall may lead to security flaws
  level: warning
  scwCategory: ""
  enabled: true
  descriptionFile: SecurityMisconfigurationAvoidDefaultHttpFirewallReturnType.html
search:
  method:
    returnType: org.springframework.security.web.firewall.DefaultHttpFirewall
availableFixes:
- name: Use interface HttpFirewall
  actions:
  - changeType:
      type: org.springframework.security.web.firewall.HttpFirewall
- name: Use interface StrictHttpFirewall
  actions:
  - changeType:
      type: org.springframework.security.web.firewall.StrictHttpFirewall
