id: b03a3f9d-977c-4562-8abb-fa108d85e3cf
metadata:
  name: 'Immutable: avoid setters that return values'
  shortDescription: Avoid setters methods that return values
  level: warning
  scwCategory: ""
  enabled: true
search:
  method:
    with:
      modifier: public
      returnType:
        not: void
        checkInheritance: true
    name:
      matches: set.*
availableFixes:
- name: Fix the code by manual refactoring
  actions: []
