id: 30ebbaf5-1741-47dc-b31d-d2bf96df8fd1
version: 8
metadata:
  name: 'Session configuration: Cookies: Set HttpOnly flag to true'
  shortDescription: Prevent client-side scripts from accessing the cookie by setting
    the HttpOnly flag to true
  level: error
  scwCategory: ""
  enabled: true
  descriptionFile: SessionconfigurationCookiesSetHttpOnlyflagtotrue.html
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "false"
    name:
      matches: setHttpOnly
    declaration:
      type: org.apache.shiro.web.servlet.SimpleCookie
availableFixes:
- name: Set HttpOnly to true
  actions:
  - modifyArguments:
      rewrite:
        1: "true"
