id: 80b554c1-35b1-4e75-a0bd-2324a6e82aa8
version: 8
metadata:
  name: 'Security Misconfiguration: EnableWebSecurity with Debug enabled'
  shortDescription: The debug parameter on EnableWebSecurity should not be hardcoded
    to true
  level: warning
  scwCategory: misconfig
  enabled: true
search:
  annotationParameter:
    name: debug
    value:
      value: "true"
availableFixes:
- name: Fix the code by setting debug to false
  actions:
  - rewrite:
      to: debug = false
