id: scw:spring:security:stricthttpfirewall-period
version: 8
metadata:
  name: 'Security Misconfiguration: StrictHttpFirewall: Rule configuration: Reject
    URL encoded period'
  shortDescription: Rejecting the use of a URL encoded period is more secure
  level: warning
  language: java
  scwCategory: ""
  enabled: true
  descriptionFile: descriptions/RejectURLEncodedPeriod.html
search:
  methodcall:
    args:
      1:
        type: boolean
        value: "true"
    name: setAllowUrlEncodedPeriod
    type: org.springframework.security.web.firewall.StrictHttpFirewall
availableFixes:
- name: Set setAllowUrlEncodedPeriod to false
  actions:
  - modifyArguments:
      rewrite:
        1: "false"
