name: 'Publish Recipes'

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

  workflow_dispatch:

jobs:
  cookbooks:
    name: 'Publish Cookbooks'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: sudo apt-get install zip jq

      - name: Generate zip files
        run: .github/workflows/package-recipes.sh

      # Only rolling releases are enabled for now.
      # Uncomment the block below to enable tagged-version releases.

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: "v${{ github.run_id }}-${{ github.run_number }}"
      #     release_name: "v${{ github.run_id }}-${{ github.run_number }}"
      #     body: |
      #       This is an automated release containing the commited cookbooks and its recipes.
      #     draft: true
      #     prerelease: false

      # - name: Upload the artifacts
      #   id: upload_artifacts
      #   uses: skx/github-action-publish-binaries@master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     args: '*.zip'
      #     releaseId: ${{ steps.create_release.outputs.id }}

      # - name: Publish release
      #   uses: StuYarrow/publish-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     id: ${{ steps.create_release.outputs.id }}

      - name: Fetching 'Latest' tag metadata
        id: fetch-latest-tag-metadata
        env:
          CUSTOM_GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
        run: |
          FOUND_RELEASE_ID=$(.github/workflows/fetch-latest-tag.sh)
          echo '::set-output name=release_id::${FOUND_RELEASE_ID}'

      - name: Pinning artifacts in tag 'Latest'
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: '*.zip'
          # Fixed value. Should be changed if we manually modify the release 'latest' by accident
          releaseId: '${{ steps.fetch-latest-tag-metadata.release_id }}'

  index:
    needs: cookbooks
    name: 'Generate New Index'
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: sudo apt-get install jq
      
      - name: Generate new documentation
        run: .github/workflows/generate-docs.sh 'v${{ github.run_id }}-${{ github.run_number }}'

      - uses: EndBug/add-and-commit@v6
        with:
          add: 'docs'

          author_name: 'DevOps Account'
          author_email: devops@securecodewarrior.com
          message: 'Updated cookbook index'
          branch: 'master'

          token: ${{ secrets.GITHUB_TOKEN }}