name: 'Pull Request Check'

on:
  pull_request:
  workflow_dispatch:

jobs:
  validation:
    name: 'Validate Cookbook Documentation'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing Dependencies
        run: |
          sudo apt-get install zip jq pip3
          sudo pip3 install html5lib

      - name: Validate
        run: .github/workflows/pull-request-validation.sh
